// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRH1R0jmD3vPoMvBCpuehqPtB4VCjgTMQ',
    appId: '1:1032041907038:web:38f852b36e17c2602145cf',
    messagingSenderId: '1032041907038',
    projectId: 'clones-projects-2024',
    authDomain: 'clones-projects-2024.firebaseapp.com',
    storageBucket: 'clones-projects-2024.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2oGNlwLh1ctl0atSnOFdn3lToxUHm6ac',
    appId: '1:1032041907038:android:044b054e35b063a12145cf',
    messagingSenderId: '1032041907038',
    projectId: 'clones-projects-2024',
    storageBucket: 'clones-projects-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJNgAI2u6xtqtpZPkU2mHVVTPuEDzM8QA',
    appId: '1:1032041907038:ios:43ef64254bd7092e2145cf',
    messagingSenderId: '1032041907038',
    projectId: 'clones-projects-2024',
    storageBucket: 'clones-projects-2024.firebasestorage.app',
    iosBundleId: 'com.example.cloneSpotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJNgAI2u6xtqtpZPkU2mHVVTPuEDzM8QA',
    appId: '1:1032041907038:ios:43ef64254bd7092e2145cf',
    messagingSenderId: '1032041907038',
    projectId: 'clones-projects-2024',
    storageBucket: 'clones-projects-2024.firebasestorage.app',
    iosBundleId: 'com.example.cloneSpotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRH1R0jmD3vPoMvBCpuehqPtB4VCjgTMQ',
    appId: '1:1032041907038:web:74a6536c76f1bc6b2145cf',
    messagingSenderId: '1032041907038',
    projectId: 'clones-projects-2024',
    authDomain: 'clones-projects-2024.firebaseapp.com',
    storageBucket: 'clones-projects-2024.firebasestorage.app',
  );

}